### PR TITLE
Adding easymotion plugin for editor convenience.

### PR DESCRIPTION
**Pull request by Khalian**

### CODE REVIEW

**Comment by Khalian** [comment]
Or should it be a separate section called navigation or something.

**Comment by akrawchyk** [comment]
Personally, I like https://github.com/justinmk/vim-sneak for this, but @justinmk even mentions in the README that it's a "minimalist alternative" to Easymotion, so let's go for it.

@Khalian can you please make sure the entry you added is in alphabetical order? Thanks!

**Comment by akrawchyk** [comment]
Or, if you feel strongly enough about adding a Navigation section, that's fine too. If you do so, just please take the extra effort to find any other plugins already in this list that would be a better fit for the Navigation section (starting with sneak and easymotion).

**Comment by Khalian** [comment]
Fixed.

**Pull request merged**
