### PR TITLE
Added 2 plugins

### PR DESCRIPTION
**Pull request by TakayoshiMiyamoto**

### CODE REVIEW

**Comment by akrawchyk** [comment]
@TakayoshiMiyamoto thanks for providing these updates! There's contribution guidelines at [CONTRIBUTING.md](https://github.com/akrawchyk/awesome-vim/blob/master/contributing.md), but here's my initial feedback:

* vim-gitgutter's use case is covered by [vim-signify](https://github.com/mhinz/vim-signify) which is alread included here. If you'd like, please move vim-signify to the **Interface** section and keep vim-gitgutter in the **Git** section.
* Markdown syntax is already included as part of [vim-polyglot](https://github.com/sheerun/vim-polyglot), but this looks more comprehensive, :+1: on that.

**Comment by TakayoshiMiyamoto** [comment]
@akrawchyk thanks for feedback.

> If you'd like,
OK. I've moved vim-signify to the Interface section in the latest commit.

> Markdown syntax is already included as part of vim-polyglot
Yes, So I hesitated whether to write...
I think that some users (markdown-only users) do not need comprehensive vim-polyglot plugin.
I want to keep vim-markdown plugin.
What do you think?

**Comment by akrawchyk** [comment]
@TakayoshiMiyamoto looks good to me :shipit:

**Comment by TakayoshiMiyamoto** [comment]
@akrawchyk thanks for merge:-)

**Pull request merged**
