### PR TITLE
Adding the most recently used vim plugin for opening files.

### PR DESCRIPTION
**Pull request by Khalian**

### CODE REVIEW

**Comment by Khalian** [comment]
Hey can we add this in?

**Comment by akrawchyk** [comment]
Sorry for the delayed response @Khalian I lost track of these PRs.

I think we already have a plugin in the list that provides this functionality and more, check out https://github.com/mhinz/vim-startify and let me know if you think that is more awesome than your suggestion.

**Comment by Khalian** [comment]
Solves different problems. Startify is a start screen. MRU can be invoked at any time, has waaaay more history tracking in it by default.

**Comment by Khalian** [comment]
Would you mind merging this in then ?

**Comment by akrawchyk** [comment]
Thanks @Khalian!

**Pull request merged**
