### PR TITLE
Add vim-mysql-plugin

### PR DESCRIPTION
**Pull request by mini-github**

### CODE REVIEW

**Comment by akrawchyk** [comment]
Hey @mini-github thanks for the idea. Please see the contribution guidelines and provide context for why this plugin is awesome. https://github.com/akrawchyk/awesome-vim/blob/master/contributing.md

**Comment by kezhenxu94** [comment]
@akrawchyk I believe it's awesome because there's no such plugin that can execute SQL statements in vim.

I personally love vim and use it to edit SQL statements, in this way, the SQL scripts can be saved and reused, and I can execute the SQL in vim directly, without opening a new terminal tab to execute. what's more, we can only execute one of the statements in a SQL file,  without this plugin, we may need to copy and paste part of the SQL script to MySQL client to execute,

**Comment by wsdjeg** [comment]
this plugin looks awesome!
在 2020年1月29日 15:41，kezhenxu94 <notifications@github.com>写道：

@akrawchyk<https://github.com/akrawchyk> I believe it's awesome because there's no such plugin that can execute SQL statements in vim.

I personally love vim and use it to edit SQL statements, in this way, the SQL scripts can be saved and reused, and I can execute the SQL in vim directly, without opening a new terminal tab to execute. what's more, we can only execute one of the statements in a SQL file, without this plugin, we may need to copy and paste part of the SQL script to MySQL client to execute,

―

**Comment by akrawchyk** [comment]
Thanks again @kezhenxu94! And @wsdjeg thanks for your work on SpaceVim!

**Pull request merged**
